### ISSUE TITLE
PHP 7.4 PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in vendor/tommyknocker/pdo-database-class/PDODb.php on line 435

### ISSUE THREAD

**Issue by parto254** [tommyknocker/pdo-database-class#10]
PHP 7.4 deprecated notice when inserting values using an array as the data source

**The code:**
``` php
$this->model->db->insert(
    'roles',
    [
        'role'=>'editor',
        'description'=>'Blog editor. Has access to blogs and blog posts.'
    ]
);
```

**The error**
> PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in vendor/tommyknocker/pdo-database-class/PDODb.php on line 435

**Comment by bas-surlinio** [comment]
Replace this line with:
if (isset($dataColumns[0])) $this->query .= ' (`'.implode('`, `',$dataColumns).'`) ';

**Comment by Phenomite** [comment]
> @bas-surlinio 
> 
> Replace this line with:
> if (isset($dataColumns[0])) $this->query .= ' (`'.implode('`, `',$dataColumns).'`) ';

As in this?

L435: 
```php
if (isset($dataColumns[0])) $this->query .= ' (`\'.implode(\'`, `\'$dataColumns).\'`) ';
```

**Comment by bas-surlinio** [comment]
Correct

**Comment by borakayalar** [comment]
//if (isset($dataColumns[0])) $this->query .= ' (`'.implode($dataColumns, '`, `').'`) ';
            if (isset($dataColumns[0])) $this->query .= ' (`' . implode('`, `', $dataColumns) . '`) ';

**Comment by gvlasov** [comment]
Will there be a release with this change?

**Comment by tommyknocker** [comment]
Yeah, sure. Releazed v1.1.1 today
