### ISSUE TITLE
Errors in README - Advanced initialization

### ISSUE THREAD

**Issue by harkor** [tommyknocker/pdo-database-class#8]
The correct initialization

`$db = new PDODb(['type' => 'mysql',
'host' => 'host',
'username' => 'username', 
 'password' => 'password',
 'dbname'=> 'databaseName',
'port' => 3306,
'prefix' => 'my_',
'charset' => 'utf8'
]);`

The error is for "dbname", in the README, it's _'db' =>_

I lost 1 hour to find the problem ;)

**Comment by tommyknocker** [comment]
Sorry for that :) Fixed, will be on packagist when next release is ready.

**Comment by harkor** [comment]
No problem, it's weird no body see this before me :)

Have a nice day
